version: '3.8'

services:
  transaction-app:
    image: transaction-app:latest
    container_name: transaction-app
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    networks:
      - my-network

  transfer-app:
    image: transfer-app:latest
    container_name: transfer-app
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
    networks:
      - my-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - transaction-app
      - transfer-app
    networks:
      - my-network
      
networks:
  my-network:
    driver: bridge